server:
  port: 8082

spring:
  application:
    name: video-platform-manage
  profiles:
    active: dev

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
  type-aliases-package: szu.model
  configuration:
    map-underscore-to-camel-case: true
redis:
  user_prefix: "login_user_"

