server:
  port: 8082

spring:
  application:
    name: video-platform-manage
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true #默认支持文件上传
      max-file-size: -1 #不做限制
      max-request-size: -1 #不做限制



mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:dao/*.xml
  type-aliases-package: szu.model
  configuration:
    map-underscore-to-camel-case: true

