server:
  port: 8084

spring:
  application:
    name: video-platform-Comment
  profiles: 
    active: dev

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  # ??????
