server:
  port: 8084

spring:
  application:
    name: video-platform-Star
  profiles: 
    active: dev


mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  # ??????

redis:
  user_prefix: "login_user_"
  login_pin: "login_pin_"
  register_pin: "register_pin_"