# 开发环境docker配置, 将端口映射到了宿主机上, 使用localhost访问
# 若不需要映射, 可以注释掉, 然后使用指定的IP来访问
version: "3.8"
services:
  mysql:
    ports:
      - "3306:3306" # MySQL默认端口
    networks:
      video-platform:
        ipv4_address: 10.11.12.101
  redis:
    ports:
      - "6379:6379" # Redis默认端口
    networks:
      video-platform:
        ipv4_address: 10.11.12.102
  mongo:
    ports:
      - "27017:27017" # MongoDB默认端口
    networks:
      video-platform:
        ipv4_address: 10.11.12.103
  minio:
    ports:
      - "9000:9000" # Minio数据端口
      - "9001:9001" # Minio控制端口
    networks:
      video-platform:
        ipv4_address: 10.11.12.104
  elasticsearch:
    ports:
      - "9200:9200" # ES控制端口
      - "9300:9300" # ES主从端口
    networks:
      video-platform:
        ipv4_address: 10.11.12.105

volumes:
  mysql-conf:
  mysql-data:
  mysql-logs:

  redis-conf:
  redis-data:
  redis-logs:

  mongo-data:
  mongo-conf:
  mongo-logs:

  minio-data:
  minio-conf:
  minio-logs:

  elasticsearch-data:
  elasticsearch-conf:
  elasticsearch-logs:
  elasticsearch-plugins:

networks:
  video-platform:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.11.12.0/24
          gateway: 10.11.12.1
