server:
  port: 8083

spring:
  application:
    name: video-platform-admin
  profiles:
    active: dev

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:dao/*.xml
  type-aliases-package: szu.model
  configuration:
    map-underscore-to-camel-case: true


redis:
  user_prefix: "login_user_"
  login_pin: "login_pin_"
  register_pin: "register_pin_"
  auth_pin: "auth_pin_"
