server:
  port: 8083

spring:
  application:
    name: video-platform-admin
  profiles:
    active: dev

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml


redis:
  user_prefix: "login_user_"