server:
  port: 8080

spring:
  application:
    name: video-platform-admin
  profiles:
    active: dev

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml


redis:
  user_prefix: "login_user_"
  login_pin: "login_pin_"
  auth_pin: "auth_pin_"