server:
  port: 8848

spring:
  application:
    name: mall-security
  profiles:
    active: dev #默认为开发环境
  mail:
    host: smtp.qq.com
    username: 2241375541@qq.com
    password: nufzskdyiofzecee
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    port: 587
    from: 2241375541@qq.com

mybatis:
  mapper-locations:
    - classpath:dao/*.xml


redis:
  user_prefix: "login_user_"
  login_pin: "login_pin_"
  auth_pin: "auth_pin_"

mail:
  phone: 13880970270
