server:
  port: 8080

spring:
  application:
    name: video-platform-Comment
  profiles: 
    active: dev


mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:dao/*.xml
  configuration:
    map-underscore-to-camel-case: true  # ??????
